"""First setup after tests

Revision ID: 82f5fc4481a4
Revises: 
Create Date: 2022-09-11 03:31:46.893791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f5fc4481a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('from_addr', sa.String(length=42), nullable=False),
    sa.Column('to_addr', sa.String(length=42), nullable=False),
    sa.Column('tx_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('tx_value', sa.Integer(), nullable=False),
    sa.Column('tx_gas', sa.Integer(), nullable=False),
    sa.Column('tx_gas_price', sa.BigInteger(), nullable=False),
    sa.Column('tx_action', sa.String(length=20), nullable=True),
    sa.Column('eth_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('tx_hash')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_address'), 'contact', ['address'], unique=False)
    op.create_index(op.f('ix_contact_name'), 'contact', ['name'], unique=False)
    op.create_table('labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet',
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('latest_block', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('wallet_id')
    )
    op.create_table('label_schema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_type', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('from_addr', sa.String(length=42), nullable=True),
    sa.Column('to_addr', sa.String(length=42), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('memo', sa.String(length=120), nullable=True),
    sa.Column('labels', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['labels'], ['labels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_details',
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('memo', sa.String(length=120), nullable=True),
    sa.Column('labels', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['labels'], ['labels.id'], ),
    sa.ForeignKeyConstraint(['tx_hash'], ['transactions.tx_hash'], ),
    sa.PrimaryKeyConstraint('tx_hash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_details')
    op.drop_table('label_schema')
    op.drop_table('wallet')
    op.drop_table('labels')
    op.drop_index(op.f('ix_contact_name'), table_name='contact')
    op.drop_index(op.f('ix_contact_address'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('transactions')
    # ### end Alembic commands ###
