"""First migrationn

Revision ID: 98315fee0e07
Revises: 
Create Date: 2022-09-18 17:56:07.099298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98315fee0e07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('block_number', sa.String(), nullable=False),
    sa.Column('from_addr', sa.String(length=42), nullable=False),
    sa.Column('to_addr', sa.String(length=42), nullable=False),
    sa.Column('tx_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('tx_value', sa.BigInteger(), nullable=False),
    sa.Column('tx_gas', sa.BigInteger(), nullable=False),
    sa.Column('tx_gas_price', sa.BigInteger(), nullable=False),
    sa.Column('tx_actions', sa.String(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('tx_hash')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_address'), 'user', ['address'], unique=True)
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_address'), 'contact', ['address'], unique=False)
    op.create_index(op.f('ix_contact_name'), 'contact', ['name'], unique=False)
    op.create_table('label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=True),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('last_block_height', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('label_schema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_type', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('from_addr', sa.String(length=42), nullable=True),
    sa.Column('to_addr', sa.String(length=42), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('memo', sa.String(length=120), nullable=True),
    sa.Column('labels', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['labels'], ['label.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('memo', sa.String(length=120), nullable=True),
    sa.Column('labels', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['labels'], ['label.id'], ),
    sa.ForeignKeyConstraint(['tx_hash'], ['transaction.tx_hash'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_detail')
    op.drop_table('label_schema')
    op.drop_table('wallet')
    op.drop_table('label')
    op.drop_index(op.f('ix_contact_name'), table_name='contact')
    op.drop_index(op.f('ix_contact_address'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_user_address'), table_name='user')
    op.drop_table('user')
    op.drop_table('transaction')
    # ### end Alembic commands ###
